name: fast_location
description: Um aplicativo para consulta de CEP e endereços.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Adicione estas bibliotecas aqui
  dio: ^4.0.6
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.2
  path_provider_android: ^2.0.14
  path_provider_ios: ^2.0.9
  map_launcher: ^2.2.1+1
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dependências de desenvolvimento
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  hive_generator: ^2.0.0
