name: fast_location
description: Um aplicativo para consulta de CEP e endereços.

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  flutter_mobx: ^2.0.4
  mobx: ^2.3.3+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  path_provider_android: ^2.2.10
  path_provider_foundation: ^2.4.0
  map_launcher: ^3.5.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
